services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./database:/var/www/html/database
    environment:
      - DB_PATH=/var/www/html/database/fuf.sqlite

