services:
  app:
    image: ghcr.io/slider1337/fuf-calculator:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - sqlite-data:/app/database
      - caddy-data:/data
      - caddy-config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - DB_PATH=/app/database/fuf.sqlite
      - APP_DEBUG=0
      - SERVER_NAME=fuf-calc.benna.me
      - APP_URL=${APP_URL}
      - MAILER_DSN=${MAILER_DSN}
      - MAIL_FROM=${MAIL_FROM}

volumes:
  sqlite-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local
